# Generated by Django 4.2 on 2023-05-02 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_round', models.IntegerField()),
                ('id_trial', models.CharField(max_length=255)),
                ('player', models.CharField(max_length=255)),
                ('value', models.IntegerField()),
                ('role', models.CharField(max_length=255)),
                ('new_role', models.CharField(max_length=255)),
                ('choice', models.BooleanField()),
                ('reward', models.IntegerField()),
                ('tracking', models.JSONField()),
                ('time', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_trial', models.IntegerField(default=0)),
                ('proposition', models.IntegerField(default=0)),
                ('commander_choice', models.BooleanField()),
                ('tracking', models.JSONField()),
                ('time', models.FloatField(default=0)),
                ('role', models.CharField(max_length=255)),
                ('subject_id', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
