# Generated by Django 4.2 on 2023-05-02 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='round',
            name='id_trial',
        ),
        migrations.AddField(
            model_name='round',
            name='subject_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trial',
            name='round',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='round',
            name='choice',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='round',
            name='reward',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='round',
            name='value',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='trial',
            name='commander_choice',
            field=models.BooleanField(default=False),
        ),
    ]
