# Generated by Django 4.2 on 2023-05-04 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_alter_round_subject_id_alter_trial_subject_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calibration',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('trajectories', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('subject_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('age', models.IntegerField()),
                ('genre', models.CharField(max_length=100)),
                ('profession', models.CharField(max_length=100)),
                ('main', models.CharField(max_length=100)),
                ('souris', models.CharField(max_length=100)),
            ],
        ),
    ]
